2018-03-21 09:43:01,798 ERROR: Exception on /list_of_projects [POST] [in /Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/cdcf/t-e-manager/app/projects/routes.py", line 74, in list_of_projects
    project_search = project_search.filter_by(Project.client_id==client.id).order_by(Project.name.asc())
TypeError: filter_by() takes 1 positional argument but 2 were given
2018-03-21 09:47:35,464 INFO: t-e-manager startup [in /Users/cdcf/t-e-manager/app/__init__.py:80]
2018-03-21 09:47:44,546 ERROR: Exception on /list_of_projects [POST] [in /Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/cdcf/t-e-manager/app/projects/routes.py", line 74, in list_of_projects
    project_search = project_search.filter(Project.client_id==client).order_by(Project.name.asc())
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/sqlalchemy/sql/operators.py", line 304, in __eq__
    return self.operate(eq, other)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 175, in operate
    return op(self.comparator, *other, **kwargs)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/sqlalchemy/sql/operators.py", line 304, in __eq__
    return self.operate(eq, other)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/sqlalchemy/orm/properties.py", line 270, in operate
    return op(self.__clause_element__(), *other, **kwargs)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/sqlalchemy/sql/annotation.py", line 102, in __eq__
    return self.__element.__class__.__eq__(self, other)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/sqlalchemy/sql/operators.py", line 304, in __eq__
    return self.operate(eq, other)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 686, in operate
    return op(self.comparator, *other, **kwargs)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/sqlalchemy/sql/operators.py", line 304, in __eq__
    return self.operate(eq, other)
  File "<string>", line 1, in <lambda>
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/sqlalchemy/sql/type_api.py", line 63, in operate
    return o[0](self.expr, op, *(other + o[1:]), **kwargs)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/sqlalchemy/sql/default_comparator.py", line 64, in _boolean_compare
    obj = _check_literal(expr, op, obj)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/sqlalchemy/sql/default_comparator.py", line 307, in _check_literal
    return expr._bind_param(operator, other, type_=bindparam_type)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 3815, in _bind_param
    unique=True)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 1094, in __init__
    _compared_to_operator, value)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/sqlalchemy/sql/type_api.py", line 523, in coerce_compared_value
    _coerced_type = _resolve_value_to_type(value)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/sqlalchemy/sql/sqltypes.py", line 2621, in _resolve_value_to_type
    "Object %r is not legal as a SQL literal value" % value)
sqlalchemy.exc.ArgumentError: Object <Client> is not legal as a SQL literal value
2018-03-21 09:48:37,925 INFO: t-e-manager startup [in /Users/cdcf/t-e-manager/app/__init__.py:80]
2018-03-21 09:49:30,089 INFO: t-e-manager startup [in /Users/cdcf/t-e-manager/app/__init__.py:80]
2018-03-21 09:49:43,812 ERROR: Exception on /list_of_projects [POST] [in /Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/cdcf/t-e-manager/app/projects/routes.py", line 74, in list_of_projects
    project_search = project_search.filter(Project.client_id==client.id).order_by(Project.name.asc())
AttributeError: 'NoneType' object has no attribute 'id'
2018-03-21 09:50:01,403 INFO: t-e-manager startup [in /Users/cdcf/t-e-manager/app/__init__.py:80]
2018-03-21 09:53:09,680 INFO: t-e-manager startup [in /Users/cdcf/t-e-manager/app/__init__.py:80]
2018-03-21 09:55:21,146 INFO: t-e-manager startup [in /Users/cdcf/t-e-manager/app/__init__.py:80]
2018-03-21 09:56:25,280 INFO: t-e-manager startup [in /Users/cdcf/t-e-manager/app/__init__.py:80]
2018-03-21 09:57:15,604 INFO: t-e-manager startup [in /Users/cdcf/t-e-manager/app/__init__.py:80]
2018-03-21 09:58:43,617 INFO: t-e-manager startup [in /Users/cdcf/t-e-manager/app/__init__.py:80]
2018-03-21 10:01:40,221 INFO: t-e-manager startup [in /Users/cdcf/t-e-manager/app/__init__.py:80]
2018-03-21 10:02:44,795 INFO: t-e-manager startup [in /Users/cdcf/t-e-manager/app/__init__.py:80]
2018-03-21 23:30:36,308 INFO: t-e-manager startup [in /Users/cdcf/t-e-manager/app/__init__.py:80]
2018-03-21 23:35:34,929 INFO: t-e-manager startup [in /Users/cdcf/t-e-manager/app/__init__.py:80]
2018-03-21 23:36:17,931 INFO: t-e-manager startup [in /Users/cdcf/t-e-manager/app/__init__.py:80]
2018-03-21 23:36:38,665 INFO: t-e-manager startup [in /Users/cdcf/t-e-manager/app/__init__.py:80]
