2018-03-18 18:21:38,925 ERROR: Exception on /add_project [GET] [in /Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/cdcf/t-e-manager/app/projects/routes.py", line 29, in add_project
    pagination=pagination)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/cdcf/t-e-manager/app/templates/projects/add_project.html", line 3, in top-level template code
    {% import "_macros.html" as macros %}
  File "/Users/cdcf/t-e-manager/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/cdcf/t-e-manager/app/templates/base.html", line 76, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/cdcf/t-e-manager/app/templates/projects/add_project.html", line 16, in block "app_content"
    {% include 'projects/_project.html' %}
  File "/Users/cdcf/t-e-manager/app/templates/projects/_project.html", line 7, in top-level template code
    <a href="{{ url_for('clients.edit_client.html', name=project.client_project.name) }}">{{ project.client_project.name }}</a>
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'clients.edit_client.html' with values ['name']. Did you mean 'clients.edit_client' instead?
2018-03-18 18:22:02,106 INFO: t-e-manager startup [in /Users/cdcf/t-e-manager/app/__init__.py:80]
2018-03-18 18:22:04,722 ERROR: Exception on /add_project [GET] [in /Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/cdcf/t-e-manager/app/projects/routes.py", line 29, in add_project
    pagination=pagination)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/cdcf/t-e-manager/app/templates/projects/add_project.html", line 3, in top-level template code
    {% import "_macros.html" as macros %}
  File "/Users/cdcf/t-e-manager/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/cdcf/t-e-manager/app/templates/base.html", line 76, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/cdcf/t-e-manager/app/templates/projects/add_project.html", line 16, in block "app_content"
    {% include 'projects/_project.html' %}
  File "/Users/cdcf/t-e-manager/app/templates/projects/_project.html", line 7, in top-level template code
    <a href="{{ url_for('clients.edit_client', name=project.client_project.name) }}">{{ project.client_project.name }}</a>
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'clients.edit_client' with values ['name']. Did you forget to specify values ['id']?
2018-03-18 18:22:44,731 INFO: t-e-manager startup [in /Users/cdcf/t-e-manager/app/__init__.py:80]
2018-03-18 18:22:58,281 INFO: t-e-manager startup [in /Users/cdcf/t-e-manager/app/__init__.py:80]
2018-03-18 18:29:26,442 INFO: t-e-manager startup [in /Users/cdcf/t-e-manager/app/__init__.py:80]
2018-03-19 11:49:54,466 INFO: t-e-manager startup [in /Users/cdcf/t-e-manager/app/__init__.py:80]
