2018-03-15 18:31:18,395 ERROR: Exception on /add_task [GET] [in /Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/cdcf/t-e-manager/app/tasks/routes.py", line 37, in add_task
    return render_template('tasks/add_task.html', title='Add a task', form=form, tasks=tasks, pagination=pagination)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/cdcf/t-e-manager/app/templates/tasks/add_task.html", line 3, in top-level template code
    {% import "_macros.html" as macros %}
  File "/Users/cdcf/t-e-manager/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/cdcf/t-e-manager/app/templates/base.html", line 76, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/cdcf/t-e-manager/app/templates/tasks/add_task.html", line 16, in block "app_content"
    {% include 'tasks/_task.html' %}
  File "/Users/cdcf/t-e-manager/app/templates/tasks/_task.html", line 17, in top-level template code
    <u>Project:</u> <a href="{{ url_for('projects.edit_project', id=task.parent.id) }}">{{ task.parent.name }}</a><br>
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.models.Task object' has no attribute 'parent'
2018-03-17 17:55:50,935 INFO: t-e-manager startup [in /Users/cdcf/t-e-manager/app/__init__.py:80]
2018-03-17 17:57:25,495 ERROR: Exception on /add_task [GET] [in /Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/cdcf/t-e-manager/app/tasks/routes.py", line 28, in add_task
    return render_template('tasks/add_task.html', title='Add a task', form=form)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/cdcf/t-e-manager/app/templates/tasks/add_task.html", line 3, in top-level template code
    {% import "_macros.html" as macros %}
  File "/Users/cdcf/t-e-manager/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/cdcf/t-e-manager/app/templates/base.html", line 76, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/cdcf/t-e-manager/app/templates/tasks/add_task.html", line 18, in block "app_content"
    {{ macros.pagination_widget(pagination, 'tasks.add_task') }}
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/Users/cdcf/t-e-manager/app/templates/_macros.html", line 3, in template
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
  File "/Users/cdcf/t-e-manager/venv/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'pagination' is undefined
2018-03-17 18:00:50,058 INFO: t-e-manager startup [in /Users/cdcf/t-e-manager/app/__init__.py:80]
